apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ReplicaOfThree
metadata:
  name: deploy-replica-of-3
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
  parameters:
    minimum: 3